RookieDraft/rookiedraft/draft/urls.py
from django.urls import path
from . import views
from .views import LeagueListView

urlpatterns = [
    path('', views.home, name='draft-home'),
    path('draft/', views.draft, name='draft-room'),
    path('reset/<int:id>/', views.reset, name='create-draft'),
    path('draft/<int:id>/', views.access, name='draft-room'),
    path('league/', views.find, name='searched-league'),
    path('league-list/<int:id>/', LeagueListView.as_view(), name='league-list'),
    path('save/<int:id>/', views.saveorder, name='save-draft-order'),
    path('view-only/<str:key>/', views.viewonly, name='view-only'),
    path('draft/<int:id>/<int:rank>/', views.pickplayer, name='pick-player'),
    path('undo/<int:id>/', views.undo, name='undo-pick'),
    path('trade/<int:id>/', views.trade, name='trade-pick'),
    path('delete/<int:id>/', views.delete, name='delete-league'),
    path('delete/<int:id>/confirm/', views.delete_confirm, name='delete-confirm'),
    path('download/<int:id>/', views.download, name='draft-download'),
]

RookieDraft/rookiedraft/rookiedraft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login-req/', auth_views.LoginView.as_view(template_name='users/login_required.html'), name='login-req'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password-reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('',include('draft.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RookieDraft/rookiedraft/draft/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


#League
class League(models.Model):
    leagueId = models.IntegerField()
    teams = models.IntegerField(default=10)
    rounds = models.IntegerField(default=4)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    draft_order = models.CharField(max_length=500)
    curr_round = models.IntegerField()
    curr_pick = models.IntegerField()
    date_created = models.DateTimeField(default=timezone.now)
    unique_key = models.CharField(max_length=50, unique=True) #leagueId+username
    year = models.IntegerField()

    def __str__(self):
        return 'League ' + str(self.leagueId)

    def get_year(self):
        if self.date_created.month < 5:
            return self.date_created.year-1
        return self.date_created.year


#Free Agents in a league        
class Player(models.Model):
    rank = models.IntegerField()
    name = models.CharField(max_length=50)
    team = models.CharField(max_length=5)
    position = models.CharField(max_length=5)
    projection = models.IntegerField()
    points = models.IntegerField()
    drafted = models.BooleanField()
    league = models.ForeignKey(League, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

#Picks in a league
class Pick(models.Model):
    round = models.IntegerField()
    number = models.IntegerField()
    player = models.ForeignKey(Player, on_delete=models.DO_NOTHING)
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    owner = models.CharField(max_length=100)

    def __str__(self):
        return 'Pick ' + str(self.round) + '.' + str(self.number)

#Teams in a league
class Team(models.Model):
    name = models.CharField(max_length=100)
    league = models.ForeignKey(League, on_delete=models.CASCADE)

    def __str(self):
        return self.name
        



RookieDraft/rookiedraft/draft/forms.py
from django import forms
from django.forms import ModelForm
from .models import League

#League Registration Form, asks for ID, # of teams, # of rounds
class LeagueRegisterForm(ModelForm):

    class Meta:
        model = League
        exclude = ('user','draft_order','curr_round','curr_pick','date_created',)
        fields = ['leagueId', 'teams', 'rounds']
        labels = {'leagueId': "League ID", 'teams': "# of Teams", 'rounds': "# of rounds"}
        
    def __init__(self,user,*args,**kwargs):
        self.user = user
        super(LeagueRegisterForm, self).__init__(*args, **kwargs)

RookieDraft/rookiedraft/draft/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.http import HttpResponse
import requests
from subprocess import run,PIPE
import sys
import sqlite3
from os import path
from .models import Pick, Player, League, Team
from .forms import LeagueRegisterForm
from espn_api.football import League as League_espn
import pandas as pd
import re
import csv


def home(request):
    #Send League Registration Form
    form = LeagueRegisterForm(request.user)
    return render(request, 'draft/home.html', {'form': form})

@login_required
def draft(request):
    #Get info from form
    form = LeagueRegisterForm(request.user, request.POST)
    leagueID = request.POST.get('leagueId')

    #Validate League Registration Form
    #TODO: Search for year field as well when we try to delete
    if form.is_valid():
        try:
            League.objects.get(leagueId=leagueID, user=request.user).delete()
        except League.DoesNotExist:
            pass
        temp = form.save(commit=False)
        temp.user = request.user
        temp.unique_key = str(leagueID) + request.user.username
        temp.curr_round = 1
        temp.curr_pick = 1
        temp.year = League.get_year(temp)
    else:
        messages.warning(request, 'Incorrect information entered')
        return redirect('draft-home')

    #Call ESPN API
    try:
        league = League_espn(league_id = leagueID, year = temp.year)
    except Exception:
        messages.warning(request, 'No Such League with this ID')
        return redirect('draft-home')

    temp.save()
    #Get current user
    user = request.user

    #Get league info from Django database
    league_mod = League.objects.get(leagueId=leagueID, user=user)
    num_rounds = league_mod.rounds
    num_teams = league_mod.teams

    #Collect list of top free agents
    fa = league.free_agents(size=150)

    #Create list of what player info we want
    fa_info = [[fa.index(player) + 1, player.name, player.proTeam, player.position,
            player.projected_points, player.points, False] for player in fa]

    #Create list of all owners
    teams = [team.team_name for team in league.teams]

    #Initialize Draft Order
    for x in range(num_teams):
        if x+1 == num_teams:
            league_mod.draft_order += teams[x]
        else:
            league_mod.draft_order += teams[x] + ","
    league_mod.save()

    #Add players to database
    for player in fa:
            player_mod = Player(rank=fa.index(player)+1,name=player.name,team=player.proTeam,
            position=player.position,projection=player.projected_points,points=player.points,drafted=False, league=league_mod)
            player_mod.save()

    #Add teams to database
    for team in teams:
        team_mod = Team(name=team, league=league_mod)
        team_mod.save()

    player = Player(name='placeholder', position='NA',rank=0,team='NA',projection=0,points=0,drafted=True, league=league_mod)
    player.save()
    #Add picks to database
    for x in range(num_rounds):
        for y in range(num_teams):
            pick = Pick(round=x+1,number=y+1,league=league_mod, player=player, owner='')
            pick.save()

    return redirect('/reset/' + str(leagueID))

@login_required
def reset(request, id):

    #Get current user
    user = request.user

    #Get league info from Django database
    league_mod = League.objects.get(leagueId=id, user=user)
    num_rounds = league_mod.rounds
    num_teams = league_mod.teams

    players = league_mod.player_set.all()
    for player in players:
        player.drafted = False
        player.save()

    placeholder = league_mod.player_set.get(name='placeholder')
    #Add picks to database
    for pick in league_mod.pick_set.all():
        pick.player = placeholder
        pick.owner = ''
        pick.save()
    
    league_mod.curr_pick = 1
    league_mod.curr_round = 1
    league_mod.save()

    #Go to display league
    return redirect('/draft/' + str(id))

#TODO: Allow user to enter in traded picks
@login_required
def access(request, id):

    #Get League Info
    try:
        league = League.objects.get(leagueId=id, user=request.user)
    except League.DoesNotExist:
        messages.warning(request, 'You do not own a league with this ID')
        return redirect('draft-home')
    rounds = league.rounds
    teams = league.teams
    players = league.player_set.all()

    #Get player and team info
    fa_dict = [
    {
        'rank': player.rank,
        'name': player.name,
        'team': player.team,
        'position': player.position,
        'projection': player.projection,
        'points': player.points,
        'drafted':player.drafted
    } for player in players]

    #Remove double spaces from team names
    users = [re.sub('  ',' ',team.name) for team in league.team_set.all()]

    #Get draft order
    draft_order = league.draft_order.split(',')
    draft_order = [{
        'name': name,
        'position': index,
    }for name,index in zip(draft_order,range(teams))]

    #Dict of picks in draft
    picks = []
    for x in range(rounds):
        draft_round = []
        for y in range(teams):
            draft_round.append({
                'player_first': league.pick_set.get(round=x+1,number=y+1).player.name.split(' ',1)[0],
                'player_last': league.pick_set.get(round=x+1,number=y+1).player.name.split(' ',1)[-1],
                'position': league.pick_set.get(round=x+1,number=y+1).player.position,
                'team' : league.pick_set.get(round=x+1,number=y+1).player.team,
                'round': x+1,
                'number': y+1,
                'owner': league.pick_set.get(round=x+1,number=y+1).owner,
            })
        picks.append(draft_round)

    return render(request, 'draft/draftroom.html', {'players':fa_dict, 'rounds':range(rounds),'names':users, 'league':league, 'order':draft_order, 'picks':picks})

def find(request):
    #Get ID searched
    leagueId = request.POST.get('leagueId')
    
    #Check if ID is valid integer
    try:
        leagueId = int(leagueId)
    except ValueError:
        messages.warning(request, 'Invalid Value Entered')
        next = request.POST.get('next','/')
        return redirect(next)

    return redirect('/league-list/' + str(leagueId))

#TODO: Add option in draft room to set league private so it doesn't show up in this search
class LeagueListView(ListView):
    model = League
    template_name = 'draft/list.html'
    ordering = ['-date_created']
    context_object_name = 'context'
    paginate_by = 5
    def get_context_data(self, **kwargs):
        context = super(ListView,self).get_context_data(**kwargs)
        context['id'] = self.kwargs['id']
        context['size'] = len(self.get_queryset())
        return context
    def get_queryset(self):
        return League.objects.filter(leagueId=self.kwargs['id'])


@login_required
def saveorder(request, id):
    #Get League
    league = League.objects.get(leagueId=id, user=request.user)
    #Generate new order based on form
    new_order = ''
    for x in range(league.teams):
        name = 'team' + str(x)
        if x+1 == league.teams:
            new_order += request.POST.get(name)
        else:
            new_order += request.POST.get(name) + ','

    league.draft_order = new_order
    league.save()

    #Return to draft room
    return redirect('/draft/' + str(id))

#View-only version of draft room        
def viewonly(request, key):

    #Get league info from database
    league = League.objects.get(unique_key=key)
    rounds = league.rounds
    teams = league.teams
    players = league.player_set.all()

    #Free Agent information to pass to template
    fa_dict = [
    {
        'rank': player.rank,
        'name': player.name,
        'team': player.team,
        'position': player.position,
        'projection': player.projection,
        'points': player.points,
        'drafted':player.drafted
    } for player in players]

    draft_order = league.draft_order.split(',')

    #Pick information to pass to template
    picks = []
    for x in range(rounds):
        draft_round = []
        for y in range(teams):
            draft_round.append({
                'player_first': league.pick_set.get(round=x+1,number=y+1).player.name.split(' ',1)[0],
                'player_last': league.pick_set.get(round=x+1,number=y+1).player.name.split(' ',1)[-1],
                'position': league.pick_set.get(round=x+1,number=y+1).player.position,
                'team' : league.pick_set.get(round=x+1,number=y+1).player.team,
                'round': x+1,
                'number':y+1,
                'owner': league.pick_set.get(round=x+1,number=y+1).owner,

            })
        picks.append(draft_round)

    return render(request, 'draft/viewonly.html', {'players':fa_dict, 'rounds':range(rounds), 'league':league, 'order':draft_order, 'picks':picks})

#Draft Player Button
@login_required
def pickplayer(request, id, rank):

    #Get league from databse
    league = League.objects.get(leagueId=id, user=request.user)
    #Check if the draft is over
    if(league.curr_round > league.rounds):
        messages.warning(request, 'Draft is already complete')
        return redirect('/draft/' + str(id))

    #Get the current pick and link it to selected player
    otc_pick = league.pick_set.get(round=league.curr_round, number=league.curr_pick)
    picked_player = league.player_set.get(rank=rank)
    picked_player.drafted = True
    picked_player.save()

RookieDraft/rookiedraft/templates/draft/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <link rel="stylesheet" type="text/css" href="{% static 'draft/main.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>
            ESPN Rookie/FA Draft App
        </title>
    </head>
    <body>
        <header class="site-header">
            <!--Navbar-->
            <nav class="navbar navbar-expand-md navbar-dark ff-green fixed-top">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">ESPN Rookie Draft</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                  <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'draft-home' %}">Home</a>
                    <!--My Leagues Dropdown-->
                    <div class="dropdown mr-2 nav-item">
                      <button class="dropbtn dropdown-toggle"> My Leagues</span></button>
                      {% if user.is_authenticated %}
                        <div class="dropdown-content">
                          {% for league in user.league_set.all %}
                            <a href="/draft/{{league.leagueId}}/">{{league.leagueId}}</a>
                          {% endfor %}
                        </div>
                      {% endif %}
                    </div>
                    <!--League Search Bar-->
                    <form method="POST" class="input-group" novalidate>
                      {%csrf_token %}
                      <input type="search"  results="0" required placeholder="League ID" name="leagueId" value="">
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <button type="submit" class="nav-item nav-link nav" formaction="/league/"><i class="fa fa-search"></i> Find League</button>
                    </form>
                    </div>
                  <!-- Navbar Right Side -->
                  <div class="navbar-nav">
                    {% if user.is_authenticated %}
                      <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                      <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                      <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                      <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </nav>
        </header>
        <!--Bootstrap Messages-->
        <div class="container">
          {% if messages %}
            {% for message in messages%}
              <div class="alert alert-{{message.tags}}">
                {{message}}
              </div>
            {% endfor %}
          {% endif %}
            <!--Content block for children templates-->
            {% block content %}{% endblock %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>

</html>

RookieDraft/rookiedraft/templates/draft/draftroom.html
{% extends "draft/base.html" %}
{% block content%}
    <div class="container">
        <table>
            <tr>
                <!---Form to select Draft Order-->
                <form method="POST" id="draft-order">
                    {%csrf_token %}
                    {% for team in order%}
                        <th><select name="team{{team.position}}">
                            {% for name in names %} 
                                {% if name == team.name %}
                                    <option selected>{{name}}</option>
                                {% else %}
                                    <option>{{name}}</option>
                                {% endif %}
                            {% endfor %}
                        </select></th>
                    {% endfor %}
                </form>
            <!--Draft Table-->
            </tr>
            {% for round in picks%}
                <tr>
                    {% for pick in round %}
                        {% if pick.round == league.curr_round and pick.number == league.curr_pick%}
                            <td class="curr-pick">On The Clock
                        {% else %}
                            {% if pick.player_first == 'placeholder'%}
                                {% if pick.owner != '' %}
                                    <td class="pick empty"><div class="traded border-bottom">&#8250;{{pick.owner}}</div><br><br></td>
                                {% else %}
                                    <td class="pick empty"><span class="info float-right">{{pick.round}}.{{pick.number}}</span><br><br><br></td>
                                {% endif %}
                            {% else %}
                                {% if pick.position == 'QB'%}
                                    <td class="pick qb">
                                {% elif pick.position == 'RB'%}
                                    <td class="pick rb">
                                {% elif pick.position == 'WR'%}
                                    <td class="pick wr">
                                {% elif pick.position == 'TE'%}
                                    <td class="pick te">
                                {% elif pick.position == 'D/ST'%}
                                    <td class="pick dst">
                                {% elif pick.position == 'K'%}
                                    <td class="pick k">
                                {% endif %}
                                {% if pick.owner != '' %}
                                    <div class="traded border-bottom">&#8250;{{pick.owner}}</div>
                                {% else %}
                                    <div class="info">{{pick.position}} - {{pick.team}} 
                                        <span class="float-right">{{pick.round}}.{{pick.number}}</span></span></div>    
                                {% endif %}
                                {{pick.player_first}}<br>{{pick.player_last}}</td>
                            {% endif %}
                        {% endif %}    
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        
        <br><br>

        <!--Player ranking table-->
        <!--TODO: Draft button functionality-->
        <div class="row justify-content-between">
        <table class="ranking col-md-8">
            <tr class="ranking">
                <th class="ranking">Rank</th>
                <th class="ranking">Name</th>
                <th class="ranking">Team</th>
                <th class="ranking">Position</th>
                <th class="ranking">2020 Projection</th>
                <th class="ranking">2019 Points</th>
            </tr>
            {%for player in players%}
                {% if not player.name == 'placeholder' %}
                    {% if not player.drafted %}
                        <tr class="ranking">
                            <td class="ranking">{{player.rank}}</td>
                            <td class="ranking">{{player.name}}</td>
                            <td class="ranking">{{player.team}}</td>
                            <td class="ranking">{{player.position}}</td>
                            <td class="ranking">{{player.projection}}</td>
                            <td class="ranking">{{player.points}}</td>
                            <td><button type="button" onclick="document.location = '/draft/{{league.leagueId}}/{{player.rank}}/'"> Draft</button></td>
                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </table>
        <div class="col-md-3">
            <div class="content-section">
                <p class="border-bottom mb-4">Control Panel</p>
                <!--Save new draft order, submit for above form-->
                <button class="mb-2" type="submit" form="draft-order" formaction="/save/{{league.leagueId}}/">Save Draft Order</button><br>
                <button class="mb-2" type="button" onclick="document.location = '/undo/{{league.leagueId}}/'">Undo Pick</button><br>
                <!--Trade Pick form-->
                <div class="content-section mb-2">
                    <p class="border-bottom mb-2">Add Traded Pick</p>
                    <form method="POST">
                        {%csrf_token %}
                        Team:
                        <select name="team" class="mb-1" required>
                            <option selected disabled></option>
                            {% for name in names %}     
                                <option>{{name}}</option>
                            {% endfor %}
                        </select>
                        Round:
                        <input class="mb-1" type="number" name="round" min="1" max="{{league.rounds}}" required><br>
                        Pick:
                        <input class="mb-1" type="number" name="pick" min="1" max="{{league.teams}}" required><br>
                        <button type="submit" formaction="/trade/{{league.leagueId}}/">Update Pick</button> 
                    </form>
                </div>
                <button class="mb-2 danger" type="button" onclick="document.location = '/reset/{{league.leagueId}}/'">Reset Draft</button>
            </div>
        </div>
    </div>
{% endblock content %}

RookieDraft/rookiedraft/templates/draft/home.html
{% extends "draft/base.html" %}
{% load crispy_forms_tags %}
{% block content%}
    <div class="content-section col-md-8">
        <!--Register League Form-->
        <form method="post">
            {%csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register League 
                    <small class="text-muted">
                        (Account Required)
                    </small>
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" formaction="/draft/">Register League</button> 
            </div>
            
                    
        </form>
    </div>
{% endblock content %}

RookieDraft/rookiedraft/templates/draft/list.html
{% extends "draft/base.html" %}
{% block content%}
    <!--Search Results-->
    <div class="content-section col-md-8">
        <p class="border-bottom mb-4">Search returned {{leagues.count}} result(s) for "{{id}}"</p>
        <ul class="list-group">
            {% for league in leagues %}
                <li class="list-group-item list-group-item-light"><a href="/view-only/{{league.unique_key}}/">League ID: {{league.leagueId}}</a><br>
                <small class="muted-text ">Teams: {{league.teams}}, Rounds: {{league.rounds}}</small> <br>
                <small class="muted-text ">Date Created: {{league.date_created|date:"F d, Y, g:iA T"}}</small>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}